language: cpp

compiler:
  - gcc

env:
  - BUILD_MODE=debug
  - BUILD_MODE=release

before_install:
  # support c++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # latest boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  # update everything now
  - sudo apt-get update -qq

install:
  # stuff needed by us
  - sudo apt-get install -qq scons
  - sudo apt-get install -qq libdw-dev

  # stuff needed by Babeltrace
  - sudo apt-get install -qq libtool
  - sudo apt-get install -qq autoconf
  - sudo apt-get install -qq libglib2.0-dev
  - sudo apt-get install -qq bison
  - sudo apt-get install -qq flex
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install -qq libpopt-dev

  # stuff needed by tigerbeetle
  - sudo apt-get install --force-yes -qq g++-4.8
  - sudo apt-get install -qq pkg-config
  - sudo apt-get install -qq libcppunit-dev
  - sudo apt-get install -qq boost1.55
  - sudo apt-get install -qq libboost1.55-dev

  # libelf, for symbols
  - sudo apt-get install -qq libelf-dev
  - sudo apt-get install -qq libdw-dev

script:
  - export CXX=g++-4.8
  - ./bootstrap.sh
  - source ./setenv.sh
  - scons mode=$BUILD_MODE
  - ./src/test/unittests
