language: cpp

compiler:
  - gcc

env:
  - BUILD_MODE=debug
  - BUILD_MODE=release

before_install:
  # R
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

  # support C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # latest Boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  # latest 0MQ
  - sudo add-apt-repository -y ppa:chris-lea/zeromq

  # stuff needed by tigerbeetle
  - sudo add-apt-repository -y ppa:chris-lea/zeromq
  - sudo add-apt-repository -y ppa:simon-marchi/myppa

  # update everything now
  - sudo apt-get update -qq

install:
  # R
  - ./travis-tool.sh install_r Rcpp RInside

  # stuff needed by Babeltrace
  - sudo apt-get install -qq libtool
  - sudo apt-get install -qq autoconf
  - sudo apt-get install -qq libglib2.0-dev
  - sudo apt-get install -qq bison
  - sudo apt-get install -qq flex
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install -qq libpopt-dev

  # stuff needed by tigerbeetle
  - sudo apt-get install --force-yes -qq g++-4.8
  - sudo apt-get install -qq pkg-config
  - sudo apt-get install -qq libcppunit-dev
  - sudo apt-get install -qq boost1.55
  - sudo apt-get install -qq libboost1.55-dev
  - sudo apt-get install -qq libzmq3-dev

  # bfd, for symbols
  - sudo apt-get install -qq binutils-dev

  # yaml-cpp
  - wget http://yaml-cpp.googlecode.com/files/yaml-cpp-0.5.1.tar.gz
  - tar -xf yaml-cpp-0.5.1.tar.gz
  - cd yaml-cpp-0.5.1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..

  # create a history directory for the tests
  - mkdir history

script:
  - export CXX=g++-4.8
  - ./bootstrap.sh
  - source ./setenv.sh
  - scons mode=$BUILD_MODE
  - ./src/test/unittests
