/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyTestLayer */

#ifndef _Included_MyTestLayer
#define _Included_MyTestLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyTestLayer
 * Method:    volume
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_MyTestLayer_volume
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     MyTestLayer
 * Method:    printmsg
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_MyTestLayer_printmsg
  (JNIEnv *, jobject, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
