/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wrapper */

#ifndef _Included_Wrapper
#define _Included_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Wrapper
 * Method:    Volume
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Wrapper_Volume
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
