blocks:
  - trace
  - punch:
      name: demo
      exec: trace-kit-profi
      begin: tracekit:begin
      end: tracekit:end
      type: ust
  - current-state
  - profiler
  - sched-wakeup:
      io: yes
      futex: no
  - linux-sched-state
  - execution